// SPDX-License-Identifier: MIT
/**
 * The detectors that decide whether a byte may be published, and the set of
 * bytes they run over.
 *
 * **Why this is a module and not a test.** Three callers need the same answer
 * and must not be able to drift apart: `test/published-prose.test.ts` (the
 * working tree), `scripts/verify-commit-messages.mjs` (the messages of the
 * commits being pushed) and any future check over a downloaded tarball. A
 * second copy of these patterns is a second policy, and the weaker one always
 * wins.
 *
 * ## The scanned set is computed from where the bytes go, never from a list of
 * directory names
 *
 * The guard this replaces named three directories — `src`, `test`, `scripts` —
 * plus six literal markdown filenames. Ten tracked files sat outside it,
 * including `.gitlab-ci.yml`, the one file that had actually carried the
 * internal host, and `package.json`, which had carried it in a
 * `devDependencies` specifier on the registry. A named list is a requirement
 * about a set guarded by examples.
 *
 * So the set is the union of three questions asked of the tools that answer
 * them:
 *
 * | set | asked of | what it is |
 * |---|---|---|
 * | `packed` | `npm pack --dry-run --json` | the bytes npm serves |
 * | `tracked` | `git ls-files` | the bytes a public mirror gets |
 * | `built` | a walk of every directory in `package.json`'s `files` | the generated bytes, which git does not know about |
 *
 * A file in none of the three is out of scope. A file in any of them is
 * scanned. Nothing chooses.
 *
 * ## Two scopes, decided by extension, and every file must land in one
 *
 * A source file addresses a stranger reading the code. A README, a changelog or
 * a CI file legitimately addresses *this repository's own* reader — `SECURITY.md`
 * opens "This repository is the TypeScript SDK", and a guard that reddened on
 * that would be demanding the document stop being about itself. So:
 *
 * - **code** (`.ts .mts .cts .js .mjs .cjs .json`): every detector.
 * - **document** (`.md .yml .yaml`, and files with no extension such as
 *   `LICENSE`): the MARKER detectors only.
 *
 * `scopeOf` throws on anything it cannot classify, so a new extension is a
 * decision somebody makes rather than a file that silently stops being scanned.
 *
 * ## Stripping happens for one detector, not for all of them
 *
 * The predecessor stripped URLs *and* inline code spans from every markdown
 * line before every class. That made the six shipped documents blind to exactly
 * the shapes an internal host, a developer path or an internal id take in a
 * README — a link and a backticked citation. `[source](https://<internal
 * host>/…)` was invisible.
 *
 * Only the German scan strips, and it strips two things: URL-ish runs (several
 * German function words are also ordinary path segments — `/api/v1/von/`,
 * `/nach/`, `/bei/`) and **single-token** code spans (a backticked lone token is
 * a citation, and a changelog has to be able to say that a detector stopped
 * tripping on `von`). A multi-word code span is left in, because a backticked
 * German sentence is still a German sentence.
 *
 * ## Every detector carries its own fixtures
 *
 * `DETECTORS` is a list of objects, not two parallel arrays, so a detector
 * cannot be added without a `mustMatch` and a `mustNotMatch`. Seven of the
 * fifteen patterns in the predecessor had neither, and two of them could be
 * deleted outright with the whole suite green. `DETECTOR_FLOOR` below is the
 * anti-vacuity floor: deleting a detector is red.
 */

import { execFileSync } from 'node:child_process'
import { readdirSync, readFileSync, existsSync, statSync } from 'node:fs'
import { join } from 'node:path'

/**
 * German function words with no English homograph. Function words rather than a
 * topic vocabulary: prose switches language wholesale, so the cheap words are
 * the reliable detector and a noun list would miss a paragraph that happens to
 * avoid its nouns.
 *
 * `was` and `hat` are deliberately absent: both are ordinary English words, and
 * a detector that fires on "the reference was not resolved" is a detector
 * somebody deletes.
 */
const GERMAN = [
  'und', 'oder', 'nicht', 'aber', 'sondern', 'weil', 'dass', 'damit', 'wenn',
  'denn', 'doch', 'schon', 'noch', 'auch', 'nur', 'sehr', 'hier', 'dort',
  'jetzt', 'dann', 'immer', 'nie', 'alle', 'alles', 'viele', 'jede', 'jeder',
  'jedes', 'eine', 'einen', 'einem', 'einer', 'eines', 'kein', 'keine',
  'keinen', 'ist', 'sind', 'wurde', 'wurden', 'wird', 'werden', 'worden',
  'kann', 'können', 'muss', 'müssen', 'soll', 'sollen', 'darf', 'dürfen',
  'haben', 'hatte', 'hatten', 'für', 'über', 'unter', 'zwischen',
  'gegen', 'ohne', 'durch', 'nach', 'vor', 'bei', 'beim', 'zum', 'zur', 'vom',
  'aus', 'mit', 'von', 'auf', 'sich', 'ihre', 'ihrer', 'seine', 'seiner',
  'diese', 'dieser', 'dieses', 'welche', 'welcher', 'wer', 'wie',
  'warum', 'deshalb', 'daher', 'gemessen', 'gilt', 'steht', 'liegt',
]

/**
 * Each word is matched as `[Ww]ort`: a sentence-initial capital still counts,
 * an all-caps acronym does not.
 *
 * That is not tidiness. `mit` is on the list and `MIT` is this package's
 * licence, so under a case-insensitive flag `MIT License`, the npm licence
 * badge and `"license": "MIT"` are all German hits before a word of German is
 * written.
 *
 * **The residual, stated rather than closed:** German written in block
 * capitals. `**NICHT** in 3.1.0` or a heading `## WARUM DAS SO IST` passes,
 * because every word is matched as `[Ww]ort` and neither is. The strictly
 * stronger alternative — keep the case-insensitive flag and exempt the
 * standalone uppercase token `MIT` — was not taken, so this is a known miss
 * and not a class the detector covers. Nothing in a comment or a changelog
 * here writes German that way today, which is a judgement about the corpus,
 * not a guarantee about the pattern.
 */
const germanWord = (w) => `[${w[0].toUpperCase()}${w[0]}]${w.slice(1)}`

/** URL-ish runs. Removed before the German scan only. */
const URLISH = /\b[a-z][a-z0-9+.-]*:\/\/\S+|(?:^|[\s(`"'])\/[A-Za-z0-9_.:${}*-]+(?:\/[A-Za-z0-9_.:${}*-]+)+/g

/**
 * Single-token inline code spans. Removed before the German scan only.
 *
 * The token limit is the point: `` `von` `` is a citation and cannot be prose,
 * while `` `Das gilt nur hier` `` is a German sentence that happens to be inside
 * backticks. The predecessor stripped every span, of any length, before every
 * class.
 */
const CODESPAN_TOKEN = /`[^`\s]*`/g

/**
 * A host or working tree that only a maintainer can reach, **by shape**.
 *
 * Four branches: any GitLab host, any `.cloud` documentation host, any
 * WireGuard peer name, any tree renamed `.old`.
 *
 * **No literal, and that is the whole point of this constant.** A detector that
 * spells the host it hunts publishes it — the pattern becomes the leak, one
 * file along, findable by `git grep` on the public mirror's first day. Each
 * branch is strictly wider than the literal it replaces, which is the safe
 * direction: `gitlab.com` and `wg-quick` redden now too, and neither is written
 * anywhere in this package. Narrowing one back to a literal reopens the hole
 * twice over — in the published bytes, and in the pattern itself.
 *
 * **No leading `\b`, and that is deliberate.** The literals it replaces had no
 * word boundary either, so anchoring the front narrows rather than widens —
 * a host with a letter glued to its front matched the old pattern and would
 * not match an anchored new one. The single trailing guard is on `.old`, and it is written
 * `(?![a-zA-Z0-9_])` rather than `\b` because those are not the same thing in
 * both engines: JavaScript's `\b` is ASCII, Python's is Unicode-aware, so
 * `\b` alone makes the port in `bridge` miss every spelling whose neighbour is
 * an accented letter, which this file catches. An explicit ASCII class reads
 * the same in both. It
 * earns its place against one measured false positive — `config.older`, which
 * `mustNotMatch` names.
 *
 * Exported because `scripts/verify-published-types.mjs` asks the same question
 * of the packed `repository` field, and a second copy of it there would be a
 * second policy.
 */
export const INTERNAL_HOST =
  /gitlab\.(?:[a-z0-9-]+\.)*[a-z]{2,}|(?:[a-z0-9-]+\.)+cloud(?![a-zA-Z0-9_])|wg-[a-z0-9]+(?:-[a-z0-9]+)*|[a-z0-9_]+\.old(?![a-zA-Z0-9_])/i

/**
 * The repositories a path may point into. Computed against the repository's own
 * name so that `sdk/src/index.ts` is self-reference here and a sibling
 * reference in `@fleetless/contracts` — the predecessor's port dropped `sdk`
 * from the list by hand, which made the port strictly narrower than the guard
 * it came from and hid nothing in return.
 */
export const SIBLING_REPOS = ['cloud', 'console', 'bridge', 'infra', 'contracts', 'docs', 'sdk', 'web']

const repoAlternation = (self) => SIBLING_REPOS.filter((r) => r !== self).join('|')

/**
 * `[^\p{L}]` rather than `\b`, and that is not a style choice. `\b` in
 * JavaScript is an ASCII-word boundary: `ü` is not a word character to it, so
 * `\b` before one requires the PRECEDING character to be a word character,
 * which inverts the test for every German word opening with an umlaut. `Das
 * gilt über hier.` is missed and `darüber steht` is a false positive — wrong in
 * both directions at once, on exactly the words a German paragraph contains.
 */
const germanPattern = new RegExp(`(^|[^\\p{L}])(${GERMAN.map(germanWord).join('|')})([^\\p{L}]|$)`, 'u')

/**
 * @param {string} self the repository's own short name, excluded from the
 *   sibling-repository alternation.
 * @returns {{name: string, stance: boolean, pattern: RegExp, mustMatch: string[], mustNotMatch: string[]}[]}
 */
export function detectors(self) {
  const repos = repoAlternation(self)
  // Two fixtures below have to name a repository that is NOT this one, and one
  // has to name this one. Written against `self` rather than hardcoded, because
  // the same fixture table runs in every repository that adopts this module and
  // a hardcoded name silently becomes a self-reference in one of them — which
  // is how the predecessor's port came to drop `sdk` from its alternation by
  // hand and end up strictly narrower than the guard it came from.
  const sibling = SIBLING_REPOS.find((r) => r !== self)
  return [
    // ---- MARKERS: text that cannot be anything but internal. Scanned in both
    // scopes, because a document is as public as a source file.
    {
      name: 'German prose',
      stance: false,
      pattern: germanPattern,
      mustMatch: [
        'Die Cloud wusste es die ganze Zeit und warf die Markierung weg.',
        // The umlaut-initial word an ASCII `\b` boundary silently misses.
        'Eine Grenze, über die niemand spricht.',
        // A single-token span is stripped; the prose beside it is not.
        'The `von` segment ist hier nicht gemeint.',
        // Sentence-initial capital, which the case-sensitivity must still catch.
        'Über die Grenze spricht niemand.',
        // A multi-word span is NOT a citation and is not stripped.
        'The comment read `Das gilt nur mit einer Grenze` and was rewritten.',
      ],
      mustNotMatch: [
        // The three places `MIT` appears in this package's own published bytes.
        'MIT License',
        '  "license": "MIT",',
        '[![license MIT](https://img.shields.io/npm/l/@fleetless/sdk)](LICENSE)',
        // A URL whose segments are also German function words.
        'See `https://example.test/api/v1/von/bei/nach/wie` for the shape.',
        'The path `/nach/bei` is reserved.',
        // German letters INSIDE an English word, which an ASCII `\b` would claim.
        'The überflieger identifier is not a keyword here.',
        // Naming the words the detector looks for, which a changelog has to do.
        'It stopped tripping on `von`, `bei`, `nach` and `wie`.',
      ],
    },
    {
      name: 'an internal feature id (FL-0xx)',
      stance: false,
      // The prefix is the shape: an id class cannot be detected without the
      // letters that name it, so `FL-` stays. The fixture's number does not —
      // a three-digit one reads as a real item, and two digits fire this
      // pattern exactly as well.
      pattern: /FL-0\d/,
      mustMatch: ['Closed under FL-07; the route answers 409 now.'],
      mustNotMatch: ['The flag is FL_ENABLED and defaults to false.', 'Serial FL-12 is printed on the chassis.'],
    },
    {
      name: 'an internal defect id (DEF-nnn)',
      stance: false,
      // As above: `DEF-` is the class and stays; the number is invented and
      // deliberately short, so nothing here reads as a defect somebody could
      // look up.
      pattern: /DEF-\d/,
      mustMatch: ['* **Was fehlt, und wovon (W0, DEF-77).**'],
      mustNotMatch: ['The default is DEF_TIMEOUT_MS.', 'A `DEF-` prefix is not used by this API.'],
    },
    {
      name: 'an internal wave label (W1..W9x)',
      stance: false,
      // **Case-sensitive, and that is why it is a detector of its own.** The
      // wave/train detector below needs the `i` flag for `Wave 4` and `The
      // train`; this one must not have it, because `w2` is an ordinary
      // identifier and a test that names a fixture `const w2 = {}` is not a
      // leak. Merged into one case-insensitive pattern they were, and it
      // reported two variable declarations.
      pattern: /(^|[^\p{L}\d])W\d[a-e]?([^\p{L}\d]|$)/u,
      mustMatch: ['* **Was fehlt, und wovon (W0, DEF-77).**', 'Closed in W0, reopened in W9e.'],
      mustNotMatch: ['const w2 = { robots: {} }', 'The W3C spelling is different.', 'Bucket w9 holds the remainder.'],
    },
    {
      name: 'an internal wave or train label',
      stance: false,
      // Four shapes, because this codebase writes all four: the terse `W9b`,
      // the numbered `wave 4` / `train 6 review`, the determined `the wave` /
      // `one train early` / `the per-app train` / `spent two waves removing`,
      // and `the wave's gate`. Only the first two were detectable before.
      //
      // **`a wave label` is excluded on purpose.** Naming the class is not
      // using it, and a changelog and this module's own callers have to be able
      // to say what the detector looks for. A bare `\bwaves?\b` would have made
      // the guard's vocabulary unwritable, which is how a detector gets deleted
      // rather than obeyed.
      pattern: /\b(?:wave|train)s?\s+(?:\d|lead\b)|\b(?:the|this|that|a|an|each|every|next|last|later|earlier|same|whole|entire|following|previous|one|two|three|four|five|several|another)\s+(?:[a-z][a-z-]*\s+){0,2}(?:waves?|trains?)\b(?!\s+labels?\b)|\bwave(?:'s)?\s+(?:lead|gate|review|sweep|browser)\b/iu,
      mustMatch: [
        'The flag is `attempted`, not `changed` (train 9 review, C97).',
        'It was renamed for a wave 9 deletion that did not happen.',
        'NOTE (from the wave lead): the shared cloud restarts.',
        'It sent `passwordResetRequest { email }` for an entire wave of commits.',
        // An adjective between the determiner and the noun, and a quantifier
        // instead of a determiner. Both were invisible to the first version.
        'It has one producer already, one train early.',
        'The per-app train adds the second one.',
        'This is the defect this file has spent two waves removing.',
      ],
      mustNotMatch: [
        'The waveform is sampled at 40 Hz.',
        'Trained models are out of scope for this SDK.',
        // The guard's own vocabulary: a changelog has to be able to say which
        // class it swept, and this module's callers have to name it.
        'Put a hostname, a wave label or a pipeline number into a message.',
        '| internal wave labels | 134 | 0 |',
      ],
    },
    {
      name: 'an absolute path from a developer machine',
      stance: false,
      pattern: /\/home\/|\/Users\//,
      mustMatch: ['Written to /home/someone/work/pkg/dist.', 'See /Users/someone/work/notes.txt for the tally.'],
      mustNotMatch: ['The home page is served from `/`.', 'POST /api/users/me returns the caller.'],
    },
    {
      name: 'the reference robot by name',
      stance: false,
      // **The one literal that is kept on purpose.** The reference robot is
      // named in the public developer documentation, so the pattern discloses
      // nothing the docs do not; and there is no shape behind it — generalised,
      // two letters and a digit is every other identifier in this package. What
      // it keeps out of the published bytes is a test rig nobody outside can
      // reach, which is worth a detector even when the name is not a secret.
      pattern: /rx1/i,
      mustMatch: ['Verified against rx1 rather than a container.', 'ssh wg-RX1-example'],
      mustNotMatch: ['The register is RX_1 on that board.', 'A `matrix1` field is not read.'],
    },
    {
      name: 'an internal host or workspace name',
      stance: false,
      // Four shapes, no literal. `INTERNAL_HOST` above says why, and the
      // packed-manifest check imports the same constant.
      pattern: INTERNAL_HOST,
      mustMatch: [
        // The shape that put an internal hostname on npm 48 times: a bundler's
        // comment naming the module it inlined.
        '// node_modules/.pnpm/@fleetless+contracts@git+ssh+++git@gitlab.example.test+fleetless+f/node_modules/@fleetless/contracts/dist/common.js',
        // The shape the predecessor could not see, because it stripped links
        // out of markdown before looking: a hostname inside one.
        '[source](https://gitlab.example.test/example/example)',
        'Work items live at https://docs.example.cloud/notes.',
        // The other two branches, which had no fixture at all while the pattern
        // was a list of literals.
        'The tunnel peer is wg-example-app.',
        'The previous checkout is in tree.old-2026-01.',
      ],
      mustNotMatch: [
        'The console is at https://console.fleetless.dev.',
        'A `wg0` interface is not required.',
        // The ordinary words the widened branches must not claim: a bare
        // `cloud` with no host in front of it, and `older`.
        'The shared cloud restarts on every save.',
        'It reads `config.older` from the cache directory.',
      ],
    },
    {
      name: 'a person by first name',
      stance: false,
      pattern: /Andr[eé]\b/,
      mustMatch: ['Andre confirmed the shape on the call.'],
      mustNotMatch: ['The Andrews constant is unrelated.', 'Copyright 2026 Dehne Robotik GmbH'],
    },
    {
      name: 'an internal review codename',
      stance: false,
      // Bare, not only suffixed: the live instance was `confirmed with Nimbus`,
      // and the predecessor's pattern demanded `Nimbus-W`. `Eve` and `Data` are
      // ordinary enough words that they keep the suffix requirement.
      pattern: /\b(?:Momus|Kassandra|Threepio|Argus|Nimbus|Rosie)\b|\b(?:Eve|Data|Momus|Kassandra|Threepio|Argus|Nimbus|Rosie)-W\d*[a-e]?\b/,
      mustMatch: ['confirmed with Nimbus: `time_bucket(width, captured_at)`', 'Raised by Eve-W0 and closed the same day.'],
      mustNotMatch: ['The datapoint payload is opaque data.', 'Every event carries a `data` member.'],
    },
    {
      name: 'a file only the maintainers have',
      stance: false,
      pattern: /\bCLAUDE\.md\b|\.superpowers\/|\bdocs\/superpowers\/|\bMEMORY\.md\b/,
      // No longer excused by backticks: a published comment that cites a
      // maintainer-only file cites it whether or not it is in a code span.
      mustMatch: ['A published comment cited `CLAUDE.md` and is rewritten.', 'The plan is under docs/superpowers/plans/.'],
      mustNotMatch: ['See CONTRIBUTING.md for the test rules.', 'The claude field is not part of the schema.'],
    },
    {
      name: 'an internal task or step id',
      stance: false,
      // `task 6.3` is a coordinate in a plan the reader does not have. It is
      // not a wave label and not a decision label, and it survived both.
      pattern: /\b(?:tasks?|steps?)\s+\d+\.\d+\b/i,
      mustMatch: ['They are the browser check\'s subject (task 9.7).', 'Deferred to step 8.4.'],
      mustNotMatch: ['The task id is a uuid.', 'Retry after 1.5 seconds.', 'See section 6.3 of the RFC.'],
    },
    {
      name: 'an internal pipeline or job number',
      stance: false,
      // A GitLab pipeline id is a number only a maintainer can resolve, and it
      // is the class that survived into a commit message written under the
      // constraint that forbids it.
      pattern: /\b(?:pipelines?|MRs?|merge requests?)\s+#?\d{3,}|\bjobs?\s+#?\d{4,}/i,
      mustMatch: ['Measured on pipeline 9001: this runner uses bash.', 'A retry is safe here (pipeline 9001, job 9002).'],
      mustNotMatch: ['A job id is a uuid, never an integer.', 'The 202 carries `job_id`.', 'Cancel job 7 of the queue.'],
    },

    // ---- STANCE: ordinary text addressed to the wrong reader. Code scope
    // only, because the shipped documents are legitimately about themselves.
    {
      name: 'an internal decision label',
      stance: true,
      // `[a-e]` suffix included: `D3a` is the form this codebase writes, and the
      // predecessor's trailing `(?![A-Za-z0-9])` made every suffixed label
      // invisible — `D3` matched, then the lookahead saw `a` and failed.
      //
      // **`C`, `G` and `M` need a closing bracket; `D`, `R` and `K` do not.** A
      // review finding is always written `(review, C26)` or `(G3)`, so
      // the bracket is free for those two — and without it `C0` and `C1` are
      // the C0 and C1 control-character ranges, which this codebase's own text
      // about escaping them says out loud.
      //
      // `M` joins them for a second reason: `M` is SVG's moveto command, so
      // `d="M4 12h16M4 6h16"` is a decision label 300 times over in a built
      // documentation page. Neither repository has an `M`-prefixed label to
      // lose, and a detector that reddens on every icon in a site is one
      // somebody deletes rather than obeys.
      pattern: /(?<![A-Za-z0-9])(?:spec |design )?(?:[DRK]\d{1,2}[a-e]?(?:[–\-/,] ?[DRK]?\d{1,2}[a-e]?)*(?![A-Za-z0-9])(?=[)\s.,;:]|$)|[CGM]\d{1,2}[a-e]?(?=\)))/,
      mustMatch: [
        'Fleetless renders no page for an app user (D75).',
        "(resolveLocalWaitMs's `invalid_option`, D9a), and every caller of",
        'no public page loads anything from a third-party host (spec D9)',
        'The bearer is checked for life before it is used (train 9 review, C97).',
        '// C97). The comment below is why the token is attached at all.',
        'The claim was that the assertion was already green (G88).',
      ],
      mustNotMatch: [
        'The bound is 1..10000 and the ceiling is 64 MiB.',
        'A `.dae` referencing `textures/skin.png` uploads under that name.',
        'The colour is #C1D2E3 in both themes.',
        // The control-character ranges, which this package documents escaping.
        '`JSON.stringify` escapes the C0 controls and nothing else.',
        'A C1 control never reaches the parser.',
        // SVG path data. An icon in a built page is not a decision label.
        '<path stroke-linecap="round" d="M4 12h16M4 6h16M4 18h16"/>',
        '<path fill="#ffffff" d="M76.540 44L73.174 44L73.174 30.910Z"/>',
      ],
    },
    {
      name: 'a path into another repository',
      stance: true,
      // Three shapes: a file (it ends in an extension), a directory of any depth
      // that ends in a slash, and a bare two-segment `cloud/src`. The third one
      // stops at two segments on purpose — `the cloud/bridge/job are entirely
      // untouched` is a slash-alternation in a sentence, not a path, and a
      // pattern that took any depth without a trailing slash claimed it.
      pattern: new RegExp(
        `(?<![\\w./-])(?:${repos})/(?:[A-Za-z0-9_.-]+/)*\\.?[A-Za-z0-9_-][A-Za-z0-9_.-]*\\.[A-Za-z]{1,6}(?![A-Za-z0-9])` +
          `|(?<![\\w./-])(?:${repos})(?:/[A-Za-z0-9_.-]+)+/(?![A-Za-z0-9])` +
          `|(?<![\\w./-])(?:${repos})/[A-Za-z0-9_.-]+(?![A-Za-z0-9_./-])`,
      ),
      mustMatch: [
        'Produced by `cloud/example/config.ts`.',
        `The shape is defined in ${sibling}/src/rest.ts.`,
        "Those are `infra/example/check.mjs`'s job.",
        'A generated script lives under infra/example/.',
        'The value is read from docs/example/shell.mjs.',
        // A dotfile: the shape that was in a commit message written under the
        // constraint forbidding it, and that the first pattern could not match
        // because it required the filename to open with an alphanumeric.
        `\`${sibling}/.gitlab-ci.yml\` already installs git on the same line.`,
        // A bare two-segment directory, with no trailing slash and no
        // extension. `grep` finds it nowhere in cloud/src was in a published
        // declaration comment and matched neither of the first two shapes.
        'It is produced nowhere in cloud/example.',
        // The private company site, which is in the alternation for exactly
        // this shape.
        'See web/example/index.html for it.',
      ],
      mustNotMatch: [
        'The bundle is built from `src/index.ts`.',
        // This repository's own name is not a sibling reference. Asserted
        // rather than assumed: the predecessor's port removed `sdk` from the
        // alternation by hand and hid nothing in return.
        `\`${self}/src/index.ts\` is this package's own entry point.`,
        'The route is `/api/robots/:id/config/draft`.',
        'the cloud/bridge/job are entirely untouched',
        'The window is 3/4 of the configured budget.',
      ],
    },
    {
      name: "a reference to this project rather than to the reader's",
      stance: true,
      pattern: /\bthis (?:project|repository|repo|train|wave|codebase|delta|playbook)(?:'s)?\b/i,
      mustMatch: ['the failure this project keeps paying for', "One of this project's own rules."],
      mustNotMatch: ['this server has no sessions', 'this client sends no cookies'],
    },
    {
      name: 'a reference to a document the reader does not have',
      stance: true,
      // `(?<![\w-])…(?![\w-])` rather than `\b`: `parameterSpec` is a schema in
      // this package and `parameter-spec` is its artifact filename, both of
      // which `\bspec\b` claimed. A detector that reddens on a domain term is
      // one somebody deletes rather than obeys.
      pattern: /(?<![\w-])(?:the )?(?:spec|playbook|register row|deferral register|discipline gate|gate step)(?![\w-])/i,
      mustMatch: ['the spec calls this the speed limit', 'Deferred by the playbook to a later step.'],
      mustNotMatch: [
        'RFC 6749 §5.2 permits additional members.',
        'The OpenAPI specification is generated.',
        "'parameter-spec': parameterSpec,",
        'The `parameterSpec` schema is exported from the barrel.',
      ],
    },
    {
      name: 'how the behaviour was found rather than what it is',
      stance: true,
      // Widened past `found by <Capital>`: the live instances were `found by
      // re-reading`, `discovered by looking at it`, `confirmed by the wave
      // lead` and `has already been caught by once`. Still narrow enough that
      // `the row is found by token hash` and `caught by the body schema` — both
      // correct descriptions of behaviour — stay green, because a detector that
      // reddens on those is one somebody deletes rather than obeys.
      pattern: /(?:^|[.!?]\s+|\*\*)Measured\b|\bmeasured (?:against|on|through|either|before|in a|at the)\b|\bthe first version of this\b|\bused to (?:say|read|claim)\b|\b(?:found|caught|discovered|confirmed|noticed|spotted) by (?:a |the )?(?:review|reading|re-reading|looking|inspection|hand|eye|\w+ lead\b|[A-Z])|\balready been caught by\b/,
      mustMatch: [
        'Measured against zod 4.4.3: `.meta()` merges.',
        'This comment used to say the opposite.',
        'found by re-reading rather than by a failure',
        'renders with one surface missing, discovered by looking at it',
        'confirmed by the wave lead on both REST and realtime',
        'a defect class this file has already been caught by once',
      ],
      mustNotMatch: [
        'A malformed uuid in a body is caught by the body schema first.',
        'The row is found by token hash and the previous hash is gone.',
        'A link measured below 0.5 B/s floors to 0 here.',
        'The robot is discovered by mDNS on the local segment.',
      ],
    },
  ]
}

/**
 * Anti-vacuity floor over the detector list itself. Deleting a detector — the
 * cheapest way to make a sweep look finished — is red here, and the count is
 * asserted rather than derived so that a rename cannot quietly take one out.
 */
export const DETECTOR_FLOOR = 18

/**
 * The stance half, named rather than counted.
 *
 * `@fleetless/contracts` once selected it as `MARKERS.slice(-5)` — a
 * requirement about a set guarded by an ordering, where one marker appended
 * makes a different five "the stance classes", silently, with the documents
 * then exempt from the wrong ones. Named here and cross-checked against each
 * detector's own `stance` flag by the suite, so the two have to agree.
 *
 * A detector added without a decision lands on the MARKER side, which is the
 * strict one: markers are scanned in both scopes, stance classes in code only.
 */
export const STANCE = new Set([
  'an internal decision label',
  'a path into another repository',
  "a reference to this project rather than to the reader's",
  'a reference to a document the reader does not have',
  'how the behaviour was found rather than what it is',
])

/**
 * The stance class a commit message is also held to.
 *
 * A commit message is *about* this repository, so "this repository", "the spec"
 * and a sentence about how a defect was found are its own voice and are left
 * alone. A path into a sibling repository is not: it names a file the reader of
 * a public history cannot open, and it is one of the two deviations that were
 * already in the history written under the constraint forbidding it (the other
 * was a pipeline number, which is a marker).
 */
export const COMMIT_EXTRA_STANCE = new Set(['a path into another repository'])

/** Scopes, decided by extension. `scopeOf` throws rather than guessing. */
const CODE_EXT = new Set(['.ts', '.mts', '.cts', '.tsx', '.js', '.mjs', '.cjs', '.jsx', '.json'])
const DOC_EXT = new Set(['.md', '.yml', '.yaml', '.txt', '.html', '.css'])
/** Extensionless files that are documents: licences, notices, dotfiles. */
const DOC_NO_EXT = /^(?:[A-Z][A-Z0-9_-]*|\.[a-z][a-z0-9_-]*)$/

/** @returns {'code'|'document'} */
export function scopeOf(file) {
  const base = file.slice(file.lastIndexOf('/') + 1)
  const dot = base.lastIndexOf('.')
  const ext = dot > 0 ? base.slice(dot) : ''
  if (CODE_EXT.has(ext)) return 'code'
  if (DOC_EXT.has(ext)) return 'document'
  if (ext === '' && DOC_NO_EXT.test(base)) return 'document'
  throw new Error(
    `${file}: no scope for this file. Add its extension to CODE_EXT or DOC_EXT in scripts/internal-markers.mjs — ` +
      'an unclassified file would otherwise stop being scanned without anybody deciding that.',
  )
}

/** The German scan is the only one that strips anything. */
export function normalise(line, detectorName) {
  return detectorName === 'German prose' ? line.replace(URLISH, ' ').replace(CODESPAN_TOKEN, ' ') : line
}

/**
 * Run one detector over a text and return `file:line: excerpt` for every hit.
 * @param {{name: string, pattern: RegExp}} detector
 */
export function hitsIn(detector, label, text) {
  const out = []
  const lines = text.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const m = normalise(lines[i], detector.name).match(detector.pattern)
    if (m) out.push(`${label}:${i + 1}: …${lines[i].slice(Math.max(0, m.index - 40), m.index + 80).trim()}…`)
  }
  return out
}

function walk(root, dir) {
  const out = []
  const abs = join(root, dir)
  if (!existsSync(abs)) return out
  for (const e of readdirSync(abs, { withFileTypes: true })) {
    const rel = `${dir}/${e.name}`
    if (e.isDirectory()) out.push(...walk(root, rel))
    else out.push(rel)
  }
  return out
}

/**
 * The bytes npm serves, asked of npm.
 *
 * `script-shell` is neutralised because `npm pack` runs `prepare` even under
 * `--ignore-scripts` (npm 10.9), which would rebuild `dist/` underneath a suite
 * that has already listed it — and would put tsup's own output on the stdout
 * this parses. With every script a no-op the answer arrives in 0.2 s and
 * nothing on disk moves.
 */
export function packedFiles(root) {
  const raw = execFileSync('npm', ['pack', '--dry-run', '--json'], {
    cwd: root,
    encoding: 'utf8',
    // A no-op shell, and `/usr/bin/true` rather than `/bin/true`: the latter
    // is Linux-only, so on macOS this threw at collect time and vitest
    // dropped this file's whole suite while reporting green. `/usr/bin/true`
    // is there on both.
    //
    // `ignore_scripts` rides along but cannot carry this alone. Measured by
    // deleting `dist/` and watching whether `prepare` rebuilds it: on npm
    // 11.2.0 all three of env, `--ignore-scripts` and `script_shell` suppress
    // it; on npm 10.9.3 — what node 22 ships, so what CI runs — **only
    // `script_shell` does**, and both `ignore_scripts` forms rebuild `dist/`
    // inside the vitest worker.
    env: { ...process.env, npm_config_ignore_scripts: 'true', npm_config_script_shell: '/usr/bin/true' },
    stdio: ['ignore', 'pipe', 'ignore'],
    maxBuffer: 32 * 1024 * 1024,
  })
  // npm prefixes the JSON with its own coloured notices; the document starts at
  // the first line that is exactly `[`.
  const clean = raw.replace(/\x1b\[[0-9;]*m/g, '')
  const start = clean.search(/^\[$/m)
  if (start < 0) throw new Error('npm pack --json produced no JSON array')
  return JSON.parse(clean.slice(start))[0].files.map((f) => f.path)
}

/** Directories listed in `package.json`'s `files`, walked from disk. */
export function builtFiles(root) {
  const manifest = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
  const out = []
  for (const entry of manifest.files ?? []) {
    const abs = join(root, entry)
    if (existsSync(abs) && statSync(abs).isDirectory()) out.push(...walk(root, entry))
  }
  return out
}

export function trackedFiles(root) {
  return execFileSync('git', ['ls-files', '-z'], { cwd: root, encoding: 'utf8' }).split('\0').filter(Boolean)
}

/**
 * The three sets and their union, plus the files skipped for being binary —
 * counted rather than dropped silently, so "nothing was skipped" and "the
 * skip list ate the tree" are different answers.
 */
export function publicFileSet(root) {
  const packed = packedFiles(root)
  const tracked = trackedFiles(root)
  const built = builtFiles(root)
  const union = [...new Set([...packed, ...tracked, ...built])].sort()
  const readable = []
  const binary = []
  const missing = []
  for (const f of union) {
    const abs = join(root, f)
    if (!existsSync(abs) || !statSync(abs).isFile()) {
      missing.push(f)
      continue
    }
    const head = readFileSync(abs).subarray(0, 8192)
    if (head.includes(0)) binary.push(f)
    else readable.push(f)
  }
  return { packed, tracked, built, union, readable, binary, missing }
}
